name: 'Tangro Deploy'
description: 'Deploy a zip file containing a static site to the tangro static server'
author: 'ankri'
inputs:
  zip-file:
    description: 'The path to the zip-file'
    required: true
  deploy-url:
    description: 'The URL of the API endpoint'
    required: true
  project:
    description: 'The name of the project/step/site e.g. coverage or styleguide'
    required: true
  set-status:
    description: 'When true set the status after the site has been deployed'
    default: true
runs:
  using: 'node12'
  main: 'dist/index.js'
