name: 'Tangro Deploy'
description: 'Deploy a zip file containing a static site to the tangro static server'
author: 'ankri'
inputs:
  context:
    description: 'Choose the context for the deployment. Either "branch", "sha" or "auto"'
    default: 'branch'
  zip-file:
    description: 'The path to the zip-file'
    required: true
  deploy-url:
    description: 'The URL of the API endpoint'
    required: true
  project:
    description: 'The name of the project/step/site e.g. coverage or styleguide'
    required: true
  set-status:
    description: 'When true set the status after the site has been deployed'
    default: true
  create-deployment:
    description: 'When true the action also creates a deployment'
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
